version: '2.1'
orbs:
  jest: blimmer/jest@0.2.1
  welcome: circleci/welcome-orb@0.4.1
  heroku: circleci/heroku@0.0.10
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
workflows:
  build:
    jobs:
      - jest/test
      - welcome/run
