version: '2.1'
orbs:
  jest: blimmer/jest@0.2.1
  welcome: circleci/welcome-orb@0.4.1
  heroku: circleci/heroku@0.0.10
jobs:
  netlify:
    docker:
      - image: circleci/node:13.3.0-buster
    steps:
      - run:
          name: Netlify
          command: curl -X POST -d {} ${NETLIFY_HOOK}
workflows:
  build:
    jobs:
      - jest/test
      - welcome/run
      - netlify:
          requires: 
            - jest/test
