version: '2.1'
orbs:
  jest: blimmer/jest@0.2.1
  welcome: circleci/welcome-orb@0.4.1
  heroku: circleci/heroku@0.0.10
jobs:
  build:
    macos:
    steps:
      - run:
        name: Deploy Netlify via Build Hook
        command: curl -X POST -d {} $NETLIFY_HOOK
workflows:
  # test:
  #   jobs:
  #     - jest/test
  # welcome:
  #   jobs:
  #     - welcome/run
  # heroku_deploy:
  #   jobs:
  #     - heroku/deploy-via-git
  build:
    jobs:
        - jest/test
        - welcome/run
        - netlify
